export const ANALYTICS_EVENTS = {
  policyUploaded: "policy_uploaded",
  policyParsed: "policy_parsed",
  campaignGenerated: "campaign_generated",
  campaignPublished: "campaign_published",
  assignmentStarted: "assignment_started",
  materialAcknowledged: "material_acknowledged",
  quizSubmitted: "quiz_submitted",
  quizPassed: "quiz_passed",
  moduleQuizRegenerated: "module_quiz_regenerated",
  moduleMediaUploaded: "module_media_uploaded",
  attestationCompleted: "attestation_completed",
  exportGenerated: "export_generated",
  nudgeSent: "nudge_sent",
} as const;
